/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutPagamentoRouteImport } from './routes/checkout.pagamento'
import { Route as CheckoutEnderecoRouteImport } from './routes/checkout.endereco'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPagamentoRoute = CheckoutPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutEnderecoRoute = CheckoutEnderecoRouteImport.update({
  id: '/endereco',
  path: '/endereco',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/checkout/endereco': typeof CheckoutEnderecoRoute
  '/checkout/pagamento': typeof CheckoutPagamentoRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/endereco': typeof CheckoutEnderecoRoute
  '/checkout/pagamento': typeof CheckoutPagamentoRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/checkout/endereco': typeof CheckoutEnderecoRoute
  '/checkout/pagamento': typeof CheckoutPagamentoRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/checkout/endereco'
    | '/checkout/pagamento'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout/endereco' | '/checkout/pagamento' | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/checkout/endereco'
    | '/checkout/pagamento'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/pagamento': {
      id: '/checkout/pagamento'
      path: '/pagamento'
      fullPath: '/checkout/pagamento'
      preLoaderRoute: typeof CheckoutPagamentoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/endereco': {
      id: '/checkout/endereco'
      path: '/endereco'
      fullPath: '/checkout/endereco'
      preLoaderRoute: typeof CheckoutEnderecoRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutEnderecoRoute: typeof CheckoutEnderecoRoute
  CheckoutPagamentoRoute: typeof CheckoutPagamentoRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutEnderecoRoute: CheckoutEnderecoRoute,
  CheckoutPagamentoRoute: CheckoutPagamentoRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
